server.port=3000
spring.application.name=api-gateway
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.routes[0].id=customer-service
spring.cloud.gateway.routes[0].uri=lb://customer-service
spring.cloud.gateway.routes[0].predicates[0].name=Path
spring.cloud.gateway.routes[0].predicates[0].args[0]=/customer-service/**
spring.cloud.gateway.routes[0].filters[0].name=StripPrefix
spring.cloud.gateway.routes[0].filters[0].args[0]=1

spring.cloud.gateway.routes[1].id=fund-service
spring.cloud.gateway.routes[1].uri=lb://fund-service
spring.cloud.gateway.routes[1].predicates[0].name=Path
spring.cloud.gateway.routes[1].predicates[0].args[0]=/fund-service/**
spring.cloud.gateway.routes[1].filters[0].name=StripPrefix
spring.cloud.gateway.routes[1].filters[0].args[0]=1

spring.cloud.gateway.routes[2].id=beneficiary-service
spring.cloud.gateway.routes[2].uri=lb://beneficiary-service
spring.cloud.gateway.routes[2].predicates[0].name=Path
spring.cloud.gateway.routes[2].predicates[0].args[0]=/beneficiary-service/**
spring.cloud.gateway.routes[2].filters[0].name=StripPrefix
spring.cloud.gateway.routes[2].filters[0].args[0]=1

spring.cloud.gateway.routes[3].id=approval-service
spring.cloud.gateway.routes[3].uri=lb://approval-service
spring.cloud.gateway.routes[3].predicates[0].name=Path
spring.cloud.gateway.routes[3].predicates[0].args[0]=/approval-service/**
spring.cloud.gateway.routes[3].filters[0].name=StripPrefix
spring.cloud.gateway.routes[3].filters[0].args[0]=1
